// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bw_import_impl
NumericVector bw_import_impl(std::string bw_file, std::string chrom, int start, int end);
RcppExport SEXP _bwimport_bw_import_impl(SEXP bw_fileSEXP, SEXP chromSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bw_file(bw_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type chrom(chromSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(bw_import_impl(bw_file, chrom, start, end));
    return rcpp_result_gen;
END_RCPP
}
// bw_cleanup
void bw_cleanup();
RcppExport SEXP _bwimport_bw_cleanup() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    bw_cleanup();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bwimport_bw_import_impl", (DL_FUNC) &_bwimport_bw_import_impl, 4},
    {"_bwimport_bw_cleanup", (DL_FUNC) &_bwimport_bw_cleanup, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bwimport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
