# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bw_import_impl <- function(bw_file, chrom, start, end) {
    .Call(`_bwimport_bw_import_impl`, bw_file, chrom, start, end)
}

